AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
    - vendor/**/*

Layout/LineLength:
  AutoCorrect: true
  Max: 120

Style/Documentation:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoreMacros: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  Enabled: false
